services:
  cardthemall-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: cardthemall-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=test1234
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql


volumes:
  sql_data:
